### PR TITLE
Minimize to tray

### PR DESCRIPTION
**Pull request by jaumesegarra**
Possibility to hide the application of the taskbar (creating a tray icon) and solved temporarily a problem that when listening a project this was always converting

### CODE REVIEW

**Comment by TheJaredWilcurt** [comment]
This is fantastic, thanks so much for contributing.

Here are a few things I think need addressed before this can get merged in:

1. Ensure that desktop notifications (alerts) work with the tray icon (`alerts.js`). No new features should break the existing ones.
2. Line 173 of `scout-files/_scripts/app.js` should have it's arguments uncommented.
3. Set a global flag on the `window.scout` object that states if the app is hidden or shown. Then have the tray icon menu only show `Hide` or `Show` (whichever is relavent), not both at the same time.
4. The context menu for the tray icon should be localized. It's pretty easy, just replace the string `'Hide' with `scout.localize('HIDE')`. Do the same for `scout.localize('SHOW')` and replace `Close` with `scout.localize('EXIT')` since we already have that translated. I added "Hide" and "Show" to the translation keys file. So you can pull down the latest version of `scout-app:master` to get them.
5. Have an option to switch between a tray icon and a regular icon in the taskbar/dock.

The most common pattern for this feature is to have an application that runs in the taskbar with a setting to have it minimize or close to the tray. But if that "minimize to tray" setting is not enabled, then there will be no tray icon.

What is this part doing:

```js
if (sessionStorage[item] != stats.mtime) {
```

**Comment by jaumesegarra** [comment]
Hey!
I just uploaded a new commit, in this: the app use a frame window (This allows that when clicking on close of the window the app does not close), now tray icon only shows when app is minimized and its menu is translated.

`if (sessionStorage[item] != stats.mtime) {`
Thanks to this solve a bug temporally that does the app listening to a project does not replace every second CSS files

I've been working with version 2.5.7 of the app and then I've put the changes to the latest version, so there may be some differences

**Comment by TheJaredWilcurt** [comment]
@jaumesegarra 

There seems to be some issues with what you are (and aren't) committing, I made a video so you can see:

* https://youtu.be/OlivY8c7ClM

**Comment by krmax44** [comment]
is this going to be added at some point? I'd like to see this very much.

**Comment by TheJaredWilcurt** [comment]
@krmax44 The code in this pull request isn't ready to be merged. Currently there are higher priority features that are being worked on. So this will likely not be in the next release. It is a feature we'd like though, so if you'd like to implement it and create a pull request, as long as it works and doesn't break anything, I'd merge it in.

**Comment by krmax44** [comment]
The only thing preventing the merge is the `style.css` file. @jaumesegarra can you add the style changes to the sass files instead of to the `style.css` file to avoid conflicts?

**Comment by jaumesegarra** [comment]
DONE! Check out [my repo](https://github.com/jaumesegarra/scout-app). Now the app does not close by default but minimizes. No css changes now.

**Pull request closed without merging**
