### PR TITLE
Minimize to tray

### PR DESCRIPTION
**Pull request by jaumesegarra**
Possibility to hide the application of the taskbar (creating a tray icon). Now without css changes

### CODE REVIEW

**Comment by krmax44** [comment]
flippin' awesome! thanks so much, can't wait to see this in the actual app, hope it gets merged in soon.

**Comment by TheJaredWilcurt** [comment]
@jaumesegarra 
Thanks for this, it's been merged in. It will be in the next release of Scout-App

**Comment by krmax44** [comment]
> It will be in the next release of Scout-App

When is the next update going to roll out?

**Comment by TheJaredWilcurt** [comment]
Planned for December

**Pull request merged**
